development:
  host: "dev.example.com"
  password: "password"
  api_key: "<api key>"

staging:
  host: "staging.example.com"
  email: "john@doe.net"
  api_key: "<api key>"

production:
  host: "www.example.com"
  email: "john@doe.net"
  api_key: "<api key>"