# The name of this site.
# This text displays in the back-office and can be used in templates through the `site.name` global variable.
name: "Webby"

# The site's subdomain.
# This option is for sites on multi-site engines. The value determines where the site can be accessed under the engine's
# primary domain.
subdomain: "webby"

# An array of domain aliases for the site. This option is for sites on multi-site engines.
domains: ["www.bitaculous.com", "bitaculous.com"]

# An array of locales (languages) the site is available in. The locale listed first is the site's default locale.
# Locales are specified using ISO language codes. Possible locales include `bg`, `cs`, `de`, `en`, `es`, `et`, `fr`,
# `it`, `ja`, `nb`, `nl`, `pl`, `pt-BR`, `pt`, `ru`, `sk`, `sr` or `zh-CN`.
locales: ["en", "de"]

# The site's timezone.
# This converts the server's time to the site's time zone in templates. The `TimeZone` class from Rail's ActiveSupport
# is used to interpret the string. Sample timezones: `Tokyo`, `Beijing`, `Berlin`, `Pacific Time (US & Canada)` etc.
timezone: "Berlin"

# For SEO purposes, sites may wish to add a relevant string to the title tag and include meta tags. For this purpose you
# can set values for these variables here. They can be accessed in templates through the `site.seo_title`, `site.meta_description`
# and `site.meta_keywords` variables.
seo_title: "Bitaculous"
meta_description:
  en: "Bitaculous builds websites, software and apps for web and mobile with passion and love."
  de: "Bitaculous entwickelt Websites, Software und Apps für Web und Mobile mit Leidenschaft und Liebe."
meta_keywords:
  en: "Apps, Berlin, Bitaculous, Coding, Development, Love, Mobile, Passion, Programming, Software, Web, Websites"
  de: "Apps, Bitaculous, Entwicklung, Leidenschaft, Liebe, Mobile, Programmierung, Software, Web, Websites"