# Your translations go here, to be used with the `translate` liquid filter.

en:
  en: "EN"
  de: "EN"

de:
  en: "DE"
  de: "DE"

close:
  en: "Close"
  de: "Schliessen"

contact:
  en: "Contact"
  de: "Kontakt"

imprint:
  en: "Imprint"
  de: "Impressum"

privacy:
  en: "Privacy"
  de: "Datenschutz"

errors_occurred:
  en: "The following errors occurred:"
  de: "Die folgenden Fehler sind aufgetreten:"

page_not_found:
  en: "Page not found."
  de: "Die Seite konnte leider nicht gefunden werden."