# Your translations go here, to be used with the `translate` liquid filter.
#
# Example:
#
# {{ 'hello_world' | translate }}

en:
  en: "EN"
  de: "EN"

de:
  en: "DE"
  de: "DE"

contact:
  en: "Contact"
  de: "Kontakt"

what_we_do:
  en: "What we do"
  de: "Was wir machen"