# Your translations go here, to be used with the `translate` liquid filter.
#
# Example:
#
# {{ 'hello_world' | translate }}

bitaculous_name:
  en: "Bitaculous"
  de: "Bitaculous"

bitaculous_claim:
  en: "It's all about the bits, baby!"
  de: "It's all about the bits, baby!"