# Your translations go here, to be used with the `translate` liquid filter.

en:
  en: "EN"
  de: "EN"

de:
  en: "DE"
  de: "DE"

contact:
  en: "Contact"
  de: "Kontakt"

imprint:
  en: "Imprint"
  de: "Impressum"