development:
  host: "<HOST>"
  email: "<EMAIL>"
  api_key: "<API_KEY>"
  ssl: false

staging:
  host: "<HOST>"
  email: "<EMAIL>"
  api_key: "<API_KEY>"
  ssl: false

production:
  host: "<HOST>"
  email: "<EMAIL>"
  api_key: "<API_KEY>"
  ssl: false